apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloworld-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: helloworld-storage-class
  selector:
    matchLabels:
      role: database
      env: helloworld