apiVersion: v1
kind: Service
metadata:
  name: helloworld-react-service
  labels:
    role: frontend-service
    env: helloworld
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32001
      name: http
  type: NodePort
  selector:
    role: frontend
    env: helloworld